export const glossary = [
    { term: '변수', english: 'Variable', text: '값에 붙인 이름입니다. x = 3에서 x라는 이름이 숫자 3을 가리킵니다.', lesson: 'math-01' },
    { term: '함수', english: 'Function', text: '입력을 받아 정해진 규칙으로 출력을 만드는 관계입니다. f(3)은 함수 f에 3을 넣은 결과입니다.', lesson: 'math-02' },
    { term: '미분', english: 'Derivative', text: '입력을 아주 조금 바꿀 때 출력이 얼마나 변하는지 나타내는 변화율입니다. 함수값 자체와 다릅니다.', lesson: 'math-03' },
    { term: '적분', english: 'Integral', text: '작은 조각의 기여를 모아 전체를 구하는 연산입니다. 무엇을, 어느 범위에서, 어떤 단위로 모으는지 확인하세요.', lesson: 'math-04' },
    { term: '시그마 Σ', english: 'Summation', text: '여러 항을 더하라는 기호입니다. 같은 계산을 표본마다 반복하고 모두 더한다는 뜻으로 자주 사용합니다.', lesson: 'math-07' },
    { term: '벡터', english: 'Vector', text: '크기와 방향을 가진 값입니다. 점 두 개의 차이는 한 점에서 다른 점으로 가는 이동 벡터입니다.', lesson: 'math-05' },
    { term: '법선', english: 'Normal', text: '표면에 수직인 방향입니다. 법선이라는 이름이 길이 1을 보장하지는 않습니다.', lesson: 'math-05' },
    { term: '정규화', english: 'Normalization', text: '문맥에 따라 기준을 맞추는 연산입니다. 벡터 정규화는 방향을 유지하며 길이를 1로 만듭니다. 확률분포 정규화는 전체 합이나 적분을 1로 맞춥니다.', lesson: 'math-05' },
    { term: '확률밀도 PDF', english: 'Probability density', text: '단위 구간당 확률의 밀도입니다. 구간에 대해 적분해야 확률이 되므로 밀도값 자체는 1보다 클 수 있습니다.', lesson: 'math-06' },
    { term: '기댓값', english: 'Expected value', text: '주어진 확률 규칙에 따른 이론적 평균입니다. 한 번의 결과나 유한 표본의 평균과 같다는 보장은 없습니다.', lesson: 'math-06' },
    { term: '몬테카를로', english: 'Monte Carlo', text: '무작위 표본과 그 선택 규칙을 이용해 합이나 적분을 추정하는 방법입니다.', lesson: 'math-07' },
    { term: '편향과 분산', english: 'Bias and variance', text: '편향은 추정량의 기댓값과 목표의 차이입니다. 분산은 반복 결과가 평균 주변에서 얼마나 흔들리는지 나타냅니다.', lesson: 'guide-16-01' },
    { term: '반사율', english: 'Reflectance', text: '들어온 에너지 중 반사되는 비율입니다. 방향별 밀도값인 BRDF와 구분합니다.', lesson: 'guide-09-01' },
    { term: 'BRDF · BSDF', english: 'Scattering distribution', text: '입사 방향과 출사 방향에 따른 표면의 빛 반응을 나타냅니다. BRDF는 반사, BSDF는 반사와 투과를 아우르는 개념입니다.', lesson: 'guide-09-01' },
    { term: '방사휘도', english: 'Radiance', text: '투영 면적과 입체각당 빛의 일률에 해당하는 방사측정량입니다. 단위는 W/(m²·sr)이며, 광도학의 휘도와 구분합니다.', lesson: 'guide-12-01' },
    { term: '휘도', english: 'Luminance', text: '시감도를 반영한 광도학 물리량입니다. 단위는 cd/m²입니다. Radiance와 같은 뜻으로 쓰지 않습니다.', lesson: 'guide-12-01' },
    { term: '텍스처 · UV', english: 'Texture coordinates', text: '텍스처는 위치에 따른 값을 제공합니다. UV는 표면 위치를 텍스처 위치에 연결하는 두 좌표입니다.', lesson: 'guide-10-01' },
    { term: '소멸 · 통과율', english: 'Extinction · transmittance', text: '소멸은 관심 광선에서 빛이 빠져나가는 효과입니다. 통과율은 구간을 지나 남은 비율이며, 다른 방향에서 더해지는 빛은 별도입니다.', lesson: 'guide-11-02' },
    { term: '위상 함수', english: 'Phase function', text: '매질 내부에서 산란 전후 방향의 분포를 설명합니다. 충돌 위치를 정하는 규칙과 구분합니다.', lesson: 'guide-11-03' },
    { term: '경로 가중치', english: 'Path throughput', text: '경로를 이어 오면서 재질 반응과 각도, 샘플 선택 확률을 보정해 누적한 값입니다.', lesson: 'guide-13-01' },
    { term: 'MIS', english: 'Multiple importance sampling', text: '여러 샘플링 전략의 결과를 적절히 가중해 함께 사용하는 방법입니다. 비교하는 확률밀도의 단위를 맞춰야 합니다.', lesson: 'guide-13-02' },
    { term: '러시안 룰렛', english: 'Russian roulette', text: '일부 계산을 확률적으로 끝내고 살아남은 결과를 생존 확률로 나누어 기댓값을 유지하는 방법입니다.', lesson: 'guide-13-03' },
    { term: '상한', english: 'Majorant', text: '여기서는 구간의 실제 소멸 계수보다 작지 않은 값입니다. 위반하면 샘플링의 전제가 깨집니다.', lesson: 'guide-14-02' },
    { term: '인터페이스', english: 'Interface', text: '어떤 입력을 받고 어떤 결과를 제공하는지에 관한 약속입니다. 내부 구현을 몰라도 공통 방식으로 사용할 수 있게 합니다.', lesson: 'math-08' },
    { term: 'Wavefront', english: 'Wavefront rendering', text: '경로의 다음 작업을 큐로 분류하고 비슷한 계산을 모아서 처리하는 구조입니다. 상태 저장과 큐 관리 비용도 생깁니다.', lesson: 'guide-15-01' }
];
